build_languages:
  - name: "node"
    version: "18"
  - name: "php"
    version: "8.0"

build_commands:
  - description: "Test Command"
    command: "composer install \n npm install \n npm run build"
    halt_on_error: true